# Generated by Django 5.0.6 on 2024-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_cinema_options_cinema_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
