# Generated by Django 5.0.6 on 2024-06-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_category_cinema_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema', to='cinema_app.category'),
        ),
    ]
