# Generated by Django 5.0.6 on 2024-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_alter_cinema_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='year_production',
            field=models.PositiveIntegerField(blank=True, default=1900),
            preserve_default=False,
        ),
    ]
