# Generated by Django 5.0.6 on 2024-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_cinema_year_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='cinema_genres', to='cinema_app.genrefilm'),
        ),
    ]
