# Generated by Django 5.0.6 on 2024-06-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_genrefilm_cinema_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ['-time_create'], 'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='cinema',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cinema', to='cinema_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='cinema_genres', to='cinema_app.genrefilm', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Активный')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='year_production',
            field=models.PositiveIntegerField(blank=True, verbose_name='Год производства'),
        ),
    ]
